[package]
name = "fortuna-rust"
version = "0.1.0"
authors = ["Juan Lupión <juan.lupion@the-cocktail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
